### ISSUE TITLE
idea of checking staged files only on pre-commit hook

### ISSUE THREAD

**Issue by Kilerd** [EthanLin-TWer/react-starter#1]
the lint check on hook `eslint src --ext .ts --ext .tsx --fix && prettier --write src --loglevel silent` now is to check all file in the repo. but considering some modified files are not tracked by git and are not committed, like those temp self testing files, so is it more elegant to check the committed files only? 

like they said in there link https://stackoverflow.com/questions/54352602/find-out-staged-files-in-git-pre-commit-hook-when-using-git-commit-a

**Comment by EthanLin-TWer** [comment]
Yo. 

Linting staged files only is supported right now with [husky](https://github.com/EthanLin-TWer/react-starter/blob/master/.husky/pre-commit) and [lint-staged](https://github.com/EthanLin-TWer/react-starter/blob/master/.lintstagedrc).

The messed up part is, the `pnpm lint` script is only intended to be run one-off instead of run on every commit. It's used for me to lint the files once and have a clean codebase from some point on, then the rest should be taken care of the pre-commit hook.
